# 各个坐标系下二维码的数量
coordinates_markers_quantity:
    coordinate1: 5
    

# 各个坐标系下二维码ID
coordinates_markers_set:
    coordinate1: [20, 21, 22, 23, 24]

   

# [x, y, z, yaw, pitch, roll]
# 以全局坐标系为父坐标系，以下各个坐标系为子坐标系的TF
coordinates_TF:
    coordinate1: [0, 0, 0, 0, 0, 0 ]


