%YAML:1.0

---

aruco_bc_dict: ARUCO_MIP_36h12

aruco_bc_nmarkers: 2

aruco_bc_mInfoType: 1

aruco_bc_markers:

    - { id:36, corners:[  [-50,0.389, 3.214],

                          [-50,0.389, 3.064],

                          [-50, 0.239, 3.064],

                          [-50, 0.239, 3.214 ] ] }
   
    - { id:45, corners:[  [-50,0.172, 3.367],

                          [-50,0.172, 3.217],

                          [-50, 0.022, 3.217],

                          [-50, 0.022, 3.367 ] ] }



  