%YAML:1.0

---
# 这个是德普大厅的二维码配置文件
aruco_bc_dict: ARUCO_MIP_36h12

aruco_bc_nmarkers: 26

aruco_bc_mInfoType: 1

aruco_bc_markers:
   
    - { id:10, corners:[  [-0.075, 0.075, 0],

                          [0.075, 0.075, 0],

                          [0.075, -0.075, 0],

                          [-0.075, -0.075, 0 ] ] }

    - { id:11, corners:[  [0.248, 0.075, 0],

                          [0.398, 0.075, 0],

                          [0.398, -0.075, 0],

                          [0.248, -0.075, 0 ] ] }

    - { id:12, corners:[  [0.571, 0.075, 0],

                          [0.721, 0.075, 0],

                          [0.721, -0.075, 0],

                          [0.571, -0.075, 0 ] ] }

    - { id:13, corners:[  [0.894, 0.075, 0],

                          [1.044, 0.075, 0],

                          [1.044, -0.075, 0],

                          [0.894, -0.075, 0 ] ] }

    - { id:14, corners:[  [1.217, 0.075, 0],

                          [1.367, 0.075, 0],

                          [1.367, -0.075, 0],

                          [1.217, -0.075, 0 ] ] }

    - { id:20, corners:[  [6.217, 0.075, 0],

                          [6.367, 0.075, 0],

                          [6.367, -0.075, 0],

                          [6.217, -0.075, 0 ] ] }

    - { id:21, corners:[  [6.54, 0.075, 0],

                          [6.69, 0.075, 0],

                          [6.69, -0.075, 0],

                          [6.54, -0.075, 0 ] ] }

    - { id:22, corners:[  [6.863, 0.075, 0],

                          [7.013, 0.075, 0],

                          [7.013, -0.075, 0],

                          [6.863, -0.075, 0 ] ] }

    - { id:23, corners:[  [7.186, 0.075, 0],

                          [7.336, 0.075, 0],

                          [7.336, -0.075, 0],

                          [7.186, -0.075, 0 ] ] }

    - { id:24, corners:[  [7.509, 0.075, 0],

                          [7.659, 0.075, 0],

                          [7.659, -0.075, 0],

                          [7.509, -0.075, 0 ] ] }

    - { id:17, corners:[  [12.509, 0.075, -0.513],

                          [12.659, 0.075, -0.513],

                          [12.659, -0.075, -0.513],

                          [12.509, -0.075, -0.513 ] ] }

    - { id:18, corners:[  [12.832, 0.075, -0.513],

                          [12.982, 0.075, -0.513],

                          [12.982, -0.075, -0.513],

                          [12.832, -0.075, -0.513] ] }

    - { id:19, corners:[  [13.155, 0.075, -0.513],

                          [13.305, 0.075, -0.513],

                          [13.305, -0.075, -0.513],

                          [13.155, -0.075, -0.513] ] }   

    - { id:25, corners:[  [17.511, 0.075, -0.513],

                          [17.661, 0.075, -0.513],

                          [17.661, -0.075, -0.513],

                          [17.511, -0.075, -0.513] ] }

    - { id:26, corners:[  [17.834, 0.075, -0.513],

                          [17.984, 0.075, -0.513],

                          [17.984, -0.075, -0.513],

                          [17.834, -0.075, -0.513] ] }

    - { id:27, corners:[  [18.157, 0.075, -0.513],

                          [18.307, 0.075, -0.513],

                          [18.307, -0.075, -0.513],

                          [18.157, -0.075, -0.513] ] }

    - { id:45, corners:[  [20.366, 0.075, -0.295],

                          [20.516, 0.075, -0.295],

                          [20.516, -0.075, -0.295],

                          [20.366, -0.075, -0.295 ] ] }

    - { id:46, corners:[  [20.689, 0.075, -0.295],

                          [20.839, 0.075, -0.295],
 
                          [20.839, -0.075, -0.295],

                          [20.689, -0.075, -0.295 ] ] }

    - { id:47, corners:[  [21.012, 0.075, -0.295],

                          [21.162, 0.075, -0.295],

                          [21.162, -0.075, -0.295],

                          [21.012, -0.075, -0.295 ] ] }

    - { id:48, corners:[  [21.335, 0.075, -0.295],

                          [21.485, 0.075, -0.295],

                          [21.485, -0.075, -0.295],

                          [21.335, -0.075, -0.295 ] ] }

    - { id:49, corners:[  [21.658, 0.075, -0.295],

                          [21.808, 0.075, -0.295],

                          [21.808, -0.075, -0.295],

                          [21.658, -0.075, -0.295 ] ] }

    - { id:30, corners:[  [22.568, 0.075, 3.101],

                          [22.568, 0.075, 3.251],

                          [22.568, -0.075, 3.251],

                          [22.568, -0.075, 3.101 ] ] }                          

    - { id:31, corners:[  [22.568, 0.075, 3.424],

                          [22.568, 0.075, 3.574],

                          [22.568, -0.075, 3.574],

                          [22.568, -0.075, 3.424 ] ] }                                 

    - { id:32, corners:[  [22.568, 0.075, 3.747],

                          [22.568, 0.075, 3.897],

                          [22.568, -0.075, 3.897],

                          [22.568, -0.075, 3.747 ] ] }                                

    - { id:33, corners:[  [22.568, 0.075, 4.07],

                          [22.568, 0.075, 4.22],

                          [22.568, -0.075, 4.22],

                          [22.568, -0.075, 4.07 ] ] }                                

    - { id:34, corners:[  [22.568, 0.075, 4.393],

                          [22.568, 0.075, 4.543],

                          [22.568, -0.075, 4.543],

                          [22.568, -0.075, 4.393 ] ] }       


                          





                          
                          
