%YAML:1.0

---

aruco_bc_dict: ARUCO_MIP_36h12

aruco_bc_nmarkers: 2

aruco_bc_mInfoType: 1

aruco_bc_markers:

    - { id:36, corners:[  [-1.214, 0.389, 0],

                                     [-1.064, 0.389, 0],

                                     [-1.064,  0.239, 0],

                                     [-1.214,  0.239, 0 ] ] }
   
    - { id:45, corners:[  [-1.367, 0.172, 0],

                                          [-1.217, 0.172, 0],

                                          [-1.217,  0.022, 0],

                                          [-1.367,  0.022, 0 ] ] }



  