%YAML:1.0

---

aruco_bc_dict: ARUCO_MIP_36h12

aruco_bc_nmarkers: 25

aruco_bc_mInfoType: 1

aruco_bc_markers:

    - { id:49, corners:[  [-0.075,0.075, 0],

                          [0.075,0.075, 0],

                          [0.075, -0.075, 0],

                          [-0.075, -0.075, 0 ] ] }



    - { id:48, corners:[  [-0.398,0.075, 0],

                          [-0.248,0.075, 0],

                          [-0.248, -0.075, 0],

                          [-0.398, -0.075, 0 ] ] }



    - { id:47, corners:[  [-0.721,0.075, 0],

                          [-0.571,0.075, 0],

                          [-0.571, -0.075, 0],

                          [-0.721, -0.075, 0 ] ] }



    - { id:46, corners:[  [-1.044,0.075, 0],

                          [-0.894,0.075, 0],

                          [-0.894, -0.075, 0],

                          [-1.044, -0.075, 0 ] ] }



    - { id:45, corners:[  [-1.367,0.075, 0],

                          [-1.271,0.075, 0],

                          [-1.271, -0.075, 0],

                          [-1.367, -0.075, 0 ] ] }



    - { id:39, corners:[  [-0.245,0.292, 0],

                          [-0.095,0.292, 0],

                          [-0.095, 0.142, 0],

                          [-0.245, 0.142, 0 ] ] }



    - { id:38, corners:[  [-0.568,0.292, 0],

                          [-0.418,0.292, 0],

                          [-0.418, 0.142, 0],

                          [-0.568, 0.142, 0 ] ] }



    - { id:37, corners:[  [-0.891,0.292, 0],

                          [-0.741,0.292, 0],

                          [-0.741 ,0.142, 0],

                          [-0.891, 0.142, 0 ] ] }



    - { id:36, corners:[  [-1.214,0.292, 0],

                          [-1.064,0.292, 0],

                          [-1.064, 0.142, 0],

                          [-1.214, 0.142, 0 ] ] }



    - { id:35, corners:[  [-1.537,0.292, 0],

                          [-1.387,0.292, 0],

                          [-1.387, 0.142, 0],

                          [-1.537, 0.142, 0 ] ] }





    - { id:19, corners:[  [-5.865,0.075, 0],

                          [-5.715,0.075, 0],

                          [-5.715, -0.075, 0],

                          [-5.865, -0.075, 0 ] ] }



    - { id:18, corners:[  [-6.188,0.075, 0],

                          [-6.038,0.075, 0],

                          [-6.038, -0.075, 0],

                          [-6.188, -0.075, 0 ] ] }



    - { id:17, corners:[  [-6.511,0.075, 0],

                          [-6.361,0.075, 0],

                          [-6.361, -0.075, 0],

                          [-6.511, -0.075, 0 ] ] }



    - { id:16, corners:[  [-6.834,0.075, 0],

                          [-6.684,0.075, 0],

                          [-6.684, -0.075, 0],

                          [-6.834, -0.075, 0 ] ] }



    - { id:15, corners:[  [-7.157,0.075, 0],

                          [-7.007,0.075, 0],

                          [-7.007, -0.075, 0],

                          [-7.157, -0.075, 0 ] ] }

   

    - { id:24, corners:[  [-6.028,0.289, 0],

                          [-5.878,0.289, 0],

                          [-5.878, 0.139, 0],

                          [-6.028, 0.139, 0 ] ] }



    - { id:23, corners:[  [-6.351, 0.289, 0],

                          [-6.201, 0.289, 0],

                          [-6.201, 0.139, 0],

                          [-6.351, 0.139, 0 ] ] }



    - { id:22, corners:[  [-6.674,0.289, 0],

                          [-6.524,0.289, 0],

                          [-6.524, 0.139, 0],

                          [-6.674, 0.139, 0 ] ] }



    - { id:21, corners:[  [-6.997,0.289, 0],

                          [-6.847,0.289, 0],

                          [-6.847, 0.139, 0],

                          [-6.997, 0.139, 0 ] ] }



    - { id:20, corners:[  [-7.32,0.289, 0],

                          [-7.17,0.289, 0],

                          [-7.17, 0.139, 0],

                          [-7.32, 0.139, 0 ] ] }



    - { id:34, corners:[  [-0.0,0.289, -1.658],

                          [-0.0,0.289, -1.508],

                          [-0.0, 0.139, -1.508],

                          [-0.0, 0.139, -1.658 ] ] }



    - { id:33, corners:[  [-0.0,0.289, -1.981],

                          [-0.0,0.289, -1.831],

                          [-0.0, 0.139, -1.831],

                          [-0.0, 0.139, -1.981 ] ] }



    - { id:32, corners:[  [-0.0,0.289, -2.304],

                          [-0.0,0.289, -2.454],

                          [-0.0, 0.139, -2.454],

                          [-0.0, 0.139, -2.304 ] ] }



    - { id:31, corners:[  [-0.0,0.289, -2.627],

                          [-0.0,0.289, -2.477],

                          [-0.0, 0.139,  -2.477],

                          [-0.0, 0.139, -2.627 ] ] }



    - { id:30, corners:[  [-0.0,0.289, -2.95],

                          [-0.0,0.289, -2.8],

                          [-0.0, 0.139, -2.8],

                          [-0.0, 0.139, -2.95 ] ] }



