%YAML:1.0

---

aruco_bc_dict: ARUCO_MIP_36h12

aruco_bc_nmarkers: 15

aruco_bc_mInfoType: 1

aruco_bc_markers:
    - { id:39, corners:[  [-0.245,0.292, 0],

                          [-0.095,0.292, 0],

                          [-0.095, 0.142, 0],

                          [-0.245, 0.142, 0 ] ] }



    - { id:38, corners:[  [-0.568,0.292, 0],

                          [-0.418,0.292, 0],

                          [-0.418, 0.142, 0],

                          [-0.568, 0.142, 0 ] ] }



    - { id:37, corners:[  [-0.891,0.292, 0],

                          [-0.741,0.292, 0],

                          [-0.741 ,0.142, 0],

                          [-0.891, 0.142, 0 ] ] }



    - { id:36, corners:[  [-1.214,0.292, 0],

                          [-1.064,0.292, 0],

                          [-1.064, 0.142, 0],

                          [-1.214, 0.142, 0 ] ] }



    - { id:35, corners:[  [-1.537,0.292, 0],

                          [-1.387,0.292, 0],

                          [-1.387, 0.142, 0],

                          [-1.537, 0.142, 0 ] ] }

    - { id:24, corners:[  [-6.028,0.289, 0],

                          [-5.878,0.289, 0],

                          [-5.878, 0.139, 0],

                          [-6.028, 0.139, 0 ] ] }



    - { id:23, corners:[  [-6.351, 0.289, 0],

                          [-6.201, 0.289, 0],

                          [-6.201, 0.139, 0],

                          [-6.351, 0.139, 0 ] ] }



    - { id:22, corners:[  [-6.674,0.289, 0],

                          [-6.524,0.289, 0],

                          [-6.524, 0.139, 0],

                          [-6.674, 0.139, 0 ] ] }



    - { id:21, corners:[  [-6.997,0.289, 0],

                          [-6.847,0.289, 0],

                          [-6.847, 0.139, 0],

                          [-6.997, 0.139, 0 ] ] }



    - { id:20, corners:[  [-7.32,0.289, 0],

                          [-7.17,0.289, 0],

                          [-7.17, 0.139, 0],

                          [-7.32, 0.139, 0 ] ] }



    - { id:34, corners:[  [-9.062,0.289, -1.658],

                          [-9.062,0.289, -1.508],

                          [-9.062, 0.139, -1.508],

                          [-9.062, 0.139, -1.658 ] ] }



    - { id:33, corners:[  [-9.062,0.289, -1.981],

                          [-9.062,0.289, -1.831],

                          [-9.062, 0.139, -1.831],

                          [-9.062, 0.139, -1.981 ] ] }



    - { id:32, corners:[  [-9.062,0.289, -2.304],

                          [-9.062, 0.289, -2.154],

                          [-9.062, 0.139, -2.154],

                          [-9.062, 0.139, -2.304 ] ] }



    - { id:31, corners:[  [-9.062, 0.289, -2.627],

                          [-9.062, 0.289, -2.477],

                          [-9.062, 0.139,  -2.477],

                          [-9.062, 0.139, -2.627 ] ] }



    - { id:30, corners:[  [-9.062,0.289, -2.95],

                          [-9.062,0.289, -2.8],

                          [-9.062, 0.139, -2.8],

                          [-9.062, 0.139, -2.95 ] ] }



