%YAML:1.0
---
aruco_bc_dict: ARUCO_MIP_36h12
aruco_bc_nmarkers: 11
aruco_bc_mInfoType: 1
aruco_bc_markers:
    - { id:0, corners:[  [-0.085,0.085, 0],
                          [0.085,0.085, 0],
                          [0.085, -0.085, 0],
                          [-0.085, -0.085, 0 ] ] }

    - { id:3, corners:[  [0.405,0.085, 0],
                          [0.575,0.085, 0],
                          [0.575, -0.085, 0],
                          [0.405, -0.085, 0 ] ] }

    - { id:4, corners:[  [0.895,0.085, 0],
                          [1.065,0.085, 0],
                          [1.065, -0.085, 0],
                          [0.895, -0.085, 0 ] ] }

    - { id:5, corners:[  [1.385,0.085, 0],
                          [1.555,0.085, 0],
                          [1.555, -0.085, 0],
                          [1.385, -0.085, 0 ] ] }

    - { id:6, corners:[  [1.875,0.085, 0],
                          [2.045,0.085, 0],
                          [2.045, -0.085, 0],
                          [1.875, -0.085, 0 ] ] }

    - { id:7, corners:[  [2.365,0.085, 0],
                          [2.535,0.085, 0],
                          [2.535, -0.085, 0],
                          [2.365, -0.085, 0 ] ] }

    - { id:8, corners:[  [2.855,0.085, 0],
                          [3.025,0.085, 0],
                          [3.025, -0.085, 0],
                          [2.855, -0.085, 0 ] ] }

    - { id:9, corners:[  [3.345,0.085, 0],
                          [3.515,0.085, 0],
                          [3.515, -0.085, 0],
                          [3.345, -0.085, 0 ] ] }

    - { id:10, corners:[  [3.835,0.085, 0],
                          [4.005,0.085, 0],
                          [4.005, -0.085, 0],
                          [3.835, -0.085, 0 ] ] }

    - { id:11, corners:[  [4.325,0.085, 0],
                          [4.495,0.085, 0],
                          [4.495, -0.085, 0],
                          [4.325, -0.085, 0 ] ] }

    - { id:12, corners:[  [4.815,0.085, 0],
                          [4.985,0.085, 0],
                          [4.985, -0.085, 0],
                          [4.815, -0.085, 0 ] ] }



