%YAML:1.0

---

aruco_bc_dict: ARUCO_MIP_36h12

aruco_bc_nmarkers: 1

aruco_bc_mInfoType: 1

aruco_bc_markers:

                        

    - { id:21, corners:[  [-6.997,0.37, 0],

                          [-6.847,0.37, 0],

                          [-6.847, 0.22, 0],

                          [-6.997, 0.22, 0 ] ] }


