%YAML:1.0

---

aruco_bc_dict: ARUCO_MIP_36h12

aruco_bc_nmarkers: 30

aruco_bc_mInfoType: 1

aruco_bc_markers:
   
    - { id:49, corners:[  [-0.075,0.172, 0],

                          [0.075,0.172, 0],

                          [0.075, 0.022, 0],

                          [-0.075, 0.022, 0 ] ] }



    - { id:48, corners:[  [-0.398,0.172, 0],

                          [-0.248,0.172, 0],

                          [-0.248, 0.022, 0],

                          [-0.398, 0.022, 0 ] ] }



    - { id:47, corners:[  [-0.721,0.172, 0],

                          [-0.571,0.172, 0],

                          [-0.571, 0.022, 0],

                          [-0.721, 0.022, 0 ] ] }



    - { id:46, corners:[  [-1.044,0.172, 0],

                          [-0.894,0.172, 0],

                          [-0.894, 0.022, 0],

                          [-1.044, 0.022, 0 ] ] }



    - { id:45, corners:[  [-1.367,0.172, 0],

                          [-1.271,0.172, 0],

                          [-1.271, 0.022, 0],

                          [-1.367, 0.022, 0 ] ] }



    - { id:39, corners:[  [-0.245,0.389, 0],

                          [-0.095,0.389, 0],

                          [-0.095, 0.239, 0],

                          [-0.245, 0.239, 0 ] ] }



    - { id:38, corners:[  [-0.568,0.389, 0],

                          [-0.418,0.389, 0],

                          [-0.418, 0.239, 0],

                          [-0.568, 0.239, 0 ] ] }



    - { id:37, corners:[  [-0.891,0.389, 0],

                          [-0.741,0.389, 0],

                          [-0.741 ,0.239, 0],

                          [-0.891, 0.239, 0 ] ] }



    - { id:36, corners:[  [-1.214,0.389, 0],

                          [-1.064,0.389, 0],

                          [-1.064, 0.239, 0],

                          [-1.214, 0.239, 0 ] ] }



    - { id:35, corners:[  [-1.537,0.389, 0],

                          [-1.387,0.389, 0],

                          [-1.387, 0.239, 0],

                          [-1.537, 0.239, 0 ] ] }


                          
    - { id:24, corners:[  [-6.028,0.37, 0],

                          [-5.878,0.37, 0],

                          [-5.878, 0.22, 0],

                          [-6.028, 0.22, 0 ] ] }



    - { id:23, corners:[  [-6.351, 0.37, 0],

                          [-6.201, 0.37, 0],

                          [-6.201, 0.22, 0],

                          [-6.351, 0.22, 0 ] ] }



    - { id:22, corners:[  [-6.674,0.37, 0],

                          [-6.524,0.37, 0],

                          [-6.524, 0.22, 0],

                          [-6.674, 0.22, 0 ] ] }



    - { id:21, corners:[  [-6.997,0.37, 0],

                          [-6.847,0.37, 0],

                          [-6.847, 0.22, 0],

                          [-6.997, 0.22, 0 ] ] }



    - { id:20, corners:[  [-7.32,0.37, 0],

                          [-7.17,0.37, 0],

                          [-7.17, 0.22, 0],

                          [-7.32, 0.22, 0 ] ] }

    - { id:19, corners:[  [-5.865,0.156, 0],

                          [-5.715,0.156, 0],

                          [-5.715, 0.006, 0],

                          [-5.865, 0.006, 0 ] ] }



    - { id:18, corners:[  [-6.188,0.156, 0],

                          [-6.038,0.156, 0],

                          [-6.038, 0.006, 0],

                          [-6.188, 0.006, 0 ] ] }



    - { id:17, corners:[  [-6.511,0.156, 0],

                          [-6.361,0.156, 0],

                          [-6.361, 0.006, 0],

                          [-6.511, 0.006, 0 ] ] }



    - { id:16, corners:[  [-6.834,0.156, 0],

                          [-6.684,0.156, 0],

                          [-6.684, 0.006, 0],

                          [-6.834, 0.006, 0 ] ] }



    - { id:15, corners:[  [-7.157,0.156, 0],

                          [-7.007,0.156, 0],

                          [-7.007, 0.006, 0],

                          [-7.157, 0.006, 0 ] ] }

    - { id:34, corners:[  [-9.062,0.289, -1.658],

                          [-9.062,0.289, -1.508],

                          [-9.062, 0.139, -1.508],

                          [-9.062, 0.139, -1.658 ] ] }



    - { id:33, corners:[  [-9.062,0.289, -1.981],

                          [-9.062,0.289, -1.831],

                          [-9.062, 0.139, -1.831],

                          [-9.062, 0.139, -1.981 ] ] }



    - { id:32, corners:[  [-9.062,0.289, -2.304],

                          [-9.062, 0.289, -2.154],

                          [-9.062, 0.139, -2.154],

                          [-9.062, 0.139, -2.304 ] ] }



    - { id:31, corners:[  [-9.062, 0.289, -2.627],

                          [-9.062, 0.289, -2.477],

                          [-9.062, 0.139,  -2.477],

                          [-9.062, 0.139, -2.627 ] ] }



    - { id:30, corners:[  [-9.062,0.289, -2.95],

                          [-9.062,0.289, -2.8],

                          [-9.062, 0.139, -2.8],

                          [-9.062, 0.139, -2.95 ] ] }
                         
                         
                         
    - { id:29, corners:[  [-9.062, 0.089, -1.185],

                          [-9.062,0.089, -1.035],

                          [-9.062, -0.061, -1.035],

                          [-9.062, -0.061, -1.185 ] ] }



    - { id:28, corners:[  [-9.062, 0.089, -1.508],

                          [-9.062,0.089, -1.358],

                          [-9.062, -0.061, -1.358],

                          [-9.062, -0.061, -1.508 ] ] }



    - { id:27, corners:[  [-9.062, 0.089, -1.831],

                          [-9.062, 0.089, -1.681],

                          [-9.062, -0.061, -1.681],

                          [-9.062, -0.061, -1.831 ] ] }



    - { id:26, corners:[  [-9.062, 0.089, -2.154],

                          [-9.062, 0.089, -2.004],

                          [-9.062, -0.061,  -2.004],

                          [-9.062, -0.061, -2.154 ] ] }



    - { id:25, corners:[  [-9.062, 0.089, -2.477],

                          [-9.062, 0.089, -2.327],

                          [-9.062, -0.061, -2.327],

                          [-9.062, -0.061, -2.477 ] ] }                       


