%YAML:1.0
---
aruco_bc_dict: ARUCO_MIP_36h12
aruco_bc_nmarkers: 18
aruco_bc_mInfoType: 1
aruco_bc_markers:
    - { id:0, corners:[  [-0.085,0.085, 0],
                          [0.085,0.085, 0],
                          [0.085, -0.085, 0],
                          [-0.085, -0.085, 0 ] ] }

    - { id:3, corners:[  [0.385,0.085, 0],
                          [0.555,0.085, 0],
                          [0.555, -0.085, 0],
                          [0.385, -0.085, 0 ] ] }

    - { id:4, corners:[  [0.855,0.085, 0],
                          [1.025,0.085, 0],
                          [1.025, -0.085, 0],
                          [0.855, -0.085, 0 ] ] }

    - { id:5, corners:[  [1.325,0.085, 0],
                          [1.495,0.085, 0],
                          [1.495, -0.085, 0],
                          [1.325, -0.085, 0 ] ] }

    - { id:6, corners:[  [1.795,0.085, 0],
                          [1.965,0.085, 0],
                          [1.965, -0.085, 0],
                          [1.795, -0.085, 0 ] ] }

    - { id:7, corners:[  [2.265,0.085, 0],
                          [2.435,0.085, 0],
                          [2.435, -0.085, 0],
                          [2.265, -0.085, 0 ] ] }

    - { id:8, corners:[  [2.735,0.085, 0],
                          [2.905,0.085, 0],
                          [2.905, -0.085, 0],
                          [2.735, -0.085, 0 ] ] }

    - { id:9, corners:[  [3.205,0.085, 0],
                          [3.375,0.085, 0],
                          [3.375, -0.085, 0],
                          [3.205, -0.085, 0 ] ] }

    - { id:10, corners:[  [3.675,0.085, 0],
                          [3.845,0.085, 0],
                          [3.845, -0.085, 0],
                          [3.675, -0.085, 0 ] ] }

    - { id:11, corners:[  [4.145,0.085, 0],
                          [4.315,0.085, 0],
                          [4.315, -0.085, 0],
                          [4.415, -0.085, 0 ] ] }

    - { id:12, corners:[  [4.615,0.085, 0],
                          [4.785,0.085, 0],
                          [4.785, -0.085, 0],
                          [4.615, -0.085, 0 ] ] }

    - { id:13, corners:[  [4.971,0.085, 0.113],
                          [4.971,0.085, 0.283],
                          [4.971, -0.085, 0.283],
                          [4.971, -0.085, 0.113 ] ] }

    - { id:14, corners:[  [4.971,0.085, 0.583],
                          [4.971,0.085, 0.753],
                          [4.971, -0.085,0.753],
                          [4.971, -0.085,  0.583] ] }

    - { id:19, corners:[  [4.971,0.085, 1.053],
                          [4.971,0.085, 1.223],
                          [4.971, -0.085, 1.223],
                          [4.971, -0.085, 1.053 ] ] }

    - { id:15, corners:[  [4.971,0.085,1.523],
                          [4.971,0.085, 1.693],
                          [4.971, -0.085, 1.693],
                          [4.971, -0.085, 1.523 ] ] }


    - { id:16, corners:[  [4.971,0.085, 1.993],
                          [4.971,0.085, 2.163],
                          [4.971, -0.085, 2.163],
                          [4.971, -0.085, 1.993 ] ] }

    - { id:18, corners:[  [4.971,0.085, 2.463],
                          [4.971,0.085, 2.633],
                          [4.971, -0.085, 2.633],
                          [4.971, -0.085, 2.463 ] ] }

    - { id:17, corners:[  [4.971,0.085, 2.933],
                          [4.971,0.085, 3.103],
                          [4.971, -0.085, 3.103],
                          [4.971, -0.085, 2.933] ] }

   

