%YAML:1.0
---
aruco_bc_dict: ARUCO_MIP_36h12
aruco_bc_nmarkers: 25
aruco_bc_mInfoType: 1
aruco_bc_markers:

    - { id:45, corners:[  [-0.075,0.075, 0],

                          [0.075,0.075, 0],

                          [0.075, -0.075, 0],

                          [-0.075, -0.075, 0 ] ] }

 

    - { id:46, corners:[  [0.248,0.075, 0],

                          [0.398,0.075, 0],

                          [0.398, -0.075, 0],

                          [0.248, -0.075, 0 ] ] }

 

    - { id:47, corners:[  [0.571,0.075, 0],

                          [0.721,0.075, 0],

                          [0.721, -0.075, 0],

                          [0.571, -0.075, 0 ] ] }

 

    - { id:48, corners:[  [0.894,0.075, 0],

                          [1.044,0.075, 0],

                          [1.044, -0.075, 0],

                          [0.894, -0.075, 0 ] ] }

 

    - { id:49, corners:[  [1.217,0.075, 0],

                          [1.367,0.075, 0],

                          [1.367, -0.075, 0],

                          [1.217, -0.075, 0 ] ] }

 

    - { id:0, corners:[  [1.418,0.075, 0],

                          [1.568,0.075, 0],

                          [1.568, -0.075, 0],

                          [1.418, -0.075, 0 ] ] }

 

    - { id:1, corners:[  [1.741,0.075, 0],

                          [1.891,0.075, 0],

                          [1.891, -0.075, 0],

                          [1.741, -0.075, 0 ] ] }

 

    - { id:2, corners:[  [2.064,0.075, 0],

                          [2.214,0.075, 0],

                          [2.214, -0.075, 0],

                          [2.064, -0.075, 0 ] ] }

 

    - { id:3, corners:[  [2.387,0.075, 0],

                          [2.537,0.075, 0],

                          [2.537, -0.075, 0],

                          [2.387, -0.075, 0 ] ] }

 

    - { id:4, corners:[  [2.71,0.075, 0],

                          [2.86,0.075, 0],

                          [2.86, -0.075, 0],

                          [2.71, -0.075, 0 ] ] }

 

    - { id:5, corners:[  [2.911,0.075, 0],

                          [3.061,0.075, 0],

                          [3.061, -0.075, 0],

                          [2.911, -0.075, 0 ] ] }

 

    - { id:6, corners:[  [3.234,0.075, 0],

                          [3.384,0.075, 0],

                          [3.384, -0.075, 0],

                          [3.234, -0.075, 0 ] ] }

 

    - { id:7, corners:[  [3.557,0.075, 0],

                          [3.707,0.075, 0],

                          [3.707, -0.075, 0],

                          [3.557, -0.075, 0 ] ] }

 

    - { id:8, corners:[  [3.88,0.075, 0],

                          [4.03,0.075, 0],

                          [4.03, -0.075, 0],

                          [3.88, -0.075, 0 ] ] }

 

    - { id:9, corners:[  [4.203,0.075, 0],

                          [4.353,0.075, 0],

                          [4.353, -0.075, 0],

                          [4.203, -0.075, 0 ] ] }

 

 

    - { id:35, corners:[  [4.469,0.075, 0.025],

                          [4.469,0.075, 0.175],

                          [4.469, -0.075, 0.175],

                          [4.469, -0.075, 0.025 ] ] }

 

    - { id:36, corners:[  [4.469,0.075, 0.384],

                          [4.469,0.075, 0.498],

                          [4.469, -0.075, 0.498],

                          [4.469, -0.075, 0.384 ] ] }

 

    - { id:37, corners:[  [4.469,0.075, 0.671],

                          [4.469,0.075, 0.821],

                          [4.469, -0.075, 0.821],

                          [4.469, -0.075, 0.671 ] ] }

 

    - { id:38, corners:[  [4.469,0.075, 0.994],

                          [4.469,0.075, 1.144],

                          [4.469, -0.075, 1.144],

                          [4.469, -0.075, 0.994 ] ] }

 

    - { id:39, corners:[  [4.469,0.075, 1.317],

                          [4.469,0.075, 1.467],

                          [4.469, -0.075, 1.467],

                          [4.469, -0.075, 1.317] ] }

 

    - { id:15, corners:[  [4.469,0.075, 1.517],

                          [4.469,0.075,1.667],

                          [4.469, -0.075, 1.667],

                          [4.469, -0.075, 1.517] ] }

 

    - { id:16, corners:[  [4.469,0.075, 1.84],

                          [4.469,0.075, 1.99],

                          [4.469, -0.075, 1.99],

                          [4.469, -0.075, 1.84] ] }

 

    - { id:17, corners:[  [4.469,0.075, 2.163],

                          [4.469,0.075, 2.313],

                          [4.469, -0.075, 2.313],

                          [4.469, -0.075, 2.163 ] ] }

 

    - { id:18, corners:[  [4.469,0.075, 2.486],

                          [4.469,0.075, 2.636],

                          [4.469, -0.075, 2.636],

                          [4.469, -0.075, 2.486] ] }

 

    - { id:19, corners:[  [4.469,0.075, 2.809],

                          [4.469,0.075, 2.959],

                          [4.469, -0.075, 2.959],

                          [4.469, -0.075, 2.809 ] ] }

 